FROM node:14-alpine AS node
WORKDIR /

ADD /front/package.json .
ADD /front/yarn.lock .
RUN yarn

ADD /front ./
RUN yarn build

FROM nginx:stable as nginx
WORKDIR /

COPY --from=node /build /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
