apiVersion: v1
kind: Service
metadata:
  name: bonitto
  annotations:
#    service.beta.kubernetes.io/ncloud-load-balancer-proxy-protocol: "true"
    service.beta.kubernetes.io/ncloud-load-balancer-backend-protocol: "tcp"
spec:
  type: LoadBalancer
  selector:
    app: bonitto-web
  ports:
    - name: http
      port: 80
      targetPort: http
